stages:
  - build
  - deploy

build-chainlink-rinkby:
  stage: build
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /chainlink-rinkby/i
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR/chainlink --dockerfile $CI_PROJECT_DIR/chainlink/Dockerfile --target prod --destination $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"
    
build-chainlink-mainnet:
  stage: build
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /chainlink-mainnet/i
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR/chainlink --dockerfile $CI_PROJECT_DIR/chainlink/Dockerfile --target prod --destination $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"

build-oven:
  stage: build
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /pizza-oven/i
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --target prod --destination $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"

build-all:
  stage: build
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /all/i
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR/chainlink --dockerfile $CI_PROJECT_DIR/chainlink/Dockerfile --target prod --destination $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"-rinkby
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --target prod --destination $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"-pizza-oven



deploy-all:
  stage: deploy
  image: dtzar/helm-kubectl:3.1.2
  needs: ["build-all"]
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /all/i
  script:
    helm upgrade -i --reuse-values --set pizzaOven.tag="$CI_COMMIT_TAG"-pizza-oven --set chainlink.mainnet.enabled=false --set chainlink.image.rinkbyTag="$CI_COMMIT_TAG"-rinkby --set image.repository=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME rarepizzas rarepizza-chart

