stages:
  - build
  - deploy
image: docker:19.03.0
services:
  - docker:19.03.0-dind

variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

build-rinkeby:
  stage: build
  before_script:
    - docker info
    - apk add --no-cache py3-pip
    - pip3 install awscli
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /rinkeby/i
  script:
    - docker build -t rinkeby chainlink
    - docker tag rinkeby $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME
    - docker push $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG
    
build-mainnet:
  stage: build
  before_script:
    - docker info
    - apk add --no-cache py3-pip
    - pip3 install awscli
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /mainnet/i
  script:
    - docker build -t mainnet chainlink
    - docker tag mainnet $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME
    - docker push $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG

build-oven:
  stage: build
  before_script:
    - docker info
    - apk add --no-cache py3-pip
    - pip3 install awscli
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /oven/i
  script:
    - docker build -t oven .
    - docker tag oven $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME
    - docker push $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG

build-all:
  stage: build
  before_script:
    - docker info
    - apk add --no-cache py3-pip
    - pip3 install awscli
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /all/i
  script:
    - docker build -t pizza-oven .
    - docker tag pizza-oven $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"-oven
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME
    - docker push $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"-oven
    - docker build -t rinkeby chainlink
    - docker tag rinkeby $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"-rinkeby
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME
    - docker push $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"-rinkeby


deploy-all:
  stage: deploy
  image: dtzar/helm-kubectl:3.1.2
  needs: ["build-all"]
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /all/i
  script:
    helm upgrade -i --reuse-values --set pizzaOven.image.tag="$CI_COMMIT_TAG"-oven --set chainlink.mainnet.enabled=false --set chainlink.image.rinkebyTag="$CI_COMMIT_TAG"-rinkeby --set image.repository=$ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME rarepizzas rarepizza-chart

