stages:
  - build
  - deploy
image: docker:19.03.0
services:
  - docker:19.03.0-dind

variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

build-chainlink-rinkby:
  stage: build
  before_script:
    - docker info
    - apk add --no-cache py3-pip
    - pip3 install awscli
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /chainlink-rinkby/i
  script:
    - docker build -t chainlink-rinkby /chainlink
    - docker tag chainlink-rinkby $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG
    - docker push $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG
    
build-chainlink-rinkby:
  stage: build
  before_script:
    - docker info
    - apk add --no-cache py3-pip
    - pip3 install awscli
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /chainlink-mainnet/i
  script:
    - docker build -t chainlink-mainnet /chainlink
    - docker tag chainlink-mainnet $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG
    - docker push $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG

build-oven:
  stage: build
  before_script:
    - docker info
    - apk add --no-cache py3-pip
    - pip3 install awscli
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /pizza-oven/i
  script:
    - docker build -t pizza-oven .
    - docker tag pizza-oven $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG
    - docker push $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:$CI_COMMIT_TAG

build-all:
  stage: build
  before_script:
    - docker info
    - apk add --no-cache py3-pip
    - pip3 install awscli
  only:
    refs:
      - tags
    variables: 
      - $CI_COMMIT_TAG =~ /all/i
  script:
    - docker build -t pizza-oven .
    - docker tag pizza-oven $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"-pizza-oven
    - docker push $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"-pizza-oven
    - docker build -t chainlink-rinkby .
    - docker tag chainlink-rinkby $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"-chainlink-rinkby
    - docker push $ACCOUNT_ID_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME:"$CI_COMMIT_TAG"-chainlink-rinkby


deploy-all:
  stage: deploy
  image: dtzar/helm-kubectl:3.1.2
  needs: ["build-all"]
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /all/i
  script:
    helm upgrade -i --reuse-values --set pizzaOven.tag="$CI_COMMIT_TAG"-pizza-oven --set chainlink.mainnet.enabled=false --set chainlink.image.rinkbyTag="$CI_COMMIT_TAG"-chainlink-rinkby --set image.repository=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CLUSTER_NAME-$PROJECT_NAME rarepizzas rarepizza-chart

