# just a simple production deployment
version: "3.8"
services:
  pizza-oven:
    image: rarepizzaskitchen.azurecr.io/pizza-kitchen-python:0.0.1
    build:
      context: .
      target: prod
      network: host
    ports:
      - 8000:8000
    networks:
      - rare-pizzas
    environment:
      API_MODE: "production"
      PROJECT_NAME: "Rare Pizzas Kitchen"
      PORT: 8000

  # Add IPFS node
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:v0.7.0
    volumes:
      - ./ipfs/data:/data/ipfs # mount the ipfs data store locally
    ports:
      - 4001:4001 # ipfs swarm - (do not expose externally)
      - 5001:5001 # ipfs api - (do not expose externally)
      - 8080:8080 # ipfs gateway - expose if needed/wanted
    networks:
      - rare-pizzas
    environment:
      - IPFS_PROFILE=server

  # Add a chainlink node
  chainlink:
    image: rarepizzaskitchen.azurecr.io/chainlink:0.10.3
    build:
      context: ./chainlink
      target: prod
    entrypoint: /bin/sh -c "chainlink node start -d -p /run/secrets/password -a /run/secrets/api"
    volumes: # TODO: mount the storage directory
      - "./chainlink:/chainlink"
    ports:
      - 6688:6688
    networks:
      - rare-pizzas
    environment:
      PORT: 6688
      DATABASE_URL: postgresql://$AZURE_POSTGRES_ADMIN_USERNAME:$AZURE_POSTGRES_ADMIN_PASSWORD@$AZURE_POSTGRES_DATABASE:5432/$CHAINLINK_MAINNET_DB_NAME
    env_file:
      - "./chainlink/.env"
    secrets:
      - password
      - api

networks:
  rare-pizzas:
    driver: bridge

secrets:
  # TODO: define as env var or something
  password:
    file: "./chainlink/.password"
  api:
    file: "./chainlink/.api"