apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: chainlink-rinkby-service
  name: chainlink-rinkby
spec:
  ports:
    - name: rinkby
      port: {{ .Values.chainlink.envPort }}
      targetPort: rinkby
  selector:
    app.kubernetes.io/component: chainlink-rinkby
status:
  loadBalancer: {}
