{{ - if Values.chainlink.mainnet.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: chainlink-mainnet-pvc
  name: chainlink-mainnet-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
{{ - end }}
