apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rarepizza-ingress
  labels:
    app.kubernetes.io/component: rarepizza-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/limit-rpm: "50"
spec:
  tls:
  - hosts:
    - "rarepizza.app.chainstarters.io"
    secretName: "rarepizza-tls-secret"
  rules:
  - host: "rarepizza.app.chainstarters.io"
    http:
      paths:
      - path: /chainlink-rinkeby
        pathType: Prefix
        backend:
          service: 
            name: chainlink-rinkeby
            port: 
              name: rinkeby
      {{ if .Values.chainlink.mainnet.enabled }}
      - path: /chainlink-mainnet
        pathType: Prefix
        backend:
          service: 
            name: chainlink-mainnet
            port: 
              name: mainnet
      {{ end }}
      - path: /oven
        pathType: Prefix
        backend:
          service: 
            name: pizza-oven
            port: 
              name: pizza-oven