apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pizza-oven-pvc
  labels:
    app.kubernetes.io/component: pizza-oven-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: efs-sc